"""baseline persistent accounts

Revision ID: 23b34addd30a
Revises: 
Create Date: 2026-07-23 01:21:24.213882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23b34addd30a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('woodchuck_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('woodchuck_id', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('instrument', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('goal', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_woodchuck_profiles_woodchuck_id'), 'woodchuck_profiles', ['woodchuck_id'], unique=True)
    op.create_table('woodchuck_states',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('state_json', sa.JSON(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['woodchuck_profiles.id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('woodchuck_states')
    op.drop_index(op.f('ix_woodchuck_profiles_woodchuck_id'), table_name='woodchuck_profiles')
    op.drop_table('woodchuck_profiles')
    # ### end Alembic commands ###
