"""add practice chart verification

Revision ID: 71263ef351b4
Revises: e701fcff9301
Create Date: 2026-07-23 03:33:23.063743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71263ef351b4'
down_revision: Union[str, Sequence[str], None] = 'e701fcff9301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_charts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('practice_date', sa.Date(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('instrument', sa.String(length=50), nullable=False),
    sa.Column('note', sa.String(length=180), nullable=True),
    sa.Column('practice_details', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('credits_awarded', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['woodchuck_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_charts_practice_date'), 'practice_charts', ['practice_date'], unique=False)
    op.create_index(op.f('ix_practice_charts_profile_id'), 'practice_charts', ['profile_id'], unique=False)
    op.create_table('practice_chart_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practice_chart_id', sa.Integer(), nullable=False),
    sa.Column('verifier_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response_note', sa.String(length=300), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['practice_chart_id'], ['practice_charts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verifier_id'], ['trusted_verifiers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_chart_verifications_practice_chart_id'), 'practice_chart_verifications', ['practice_chart_id'], unique=False)
    op.create_index(op.f('ix_practice_chart_verifications_status'), 'practice_chart_verifications', ['status'], unique=False)
    op.create_index(op.f('ix_practice_chart_verifications_verifier_id'), 'practice_chart_verifications', ['verifier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_chart_verifications_verifier_id'), table_name='practice_chart_verifications')
    op.drop_index(op.f('ix_practice_chart_verifications_status'), table_name='practice_chart_verifications')
    op.drop_index(op.f('ix_practice_chart_verifications_practice_chart_id'), table_name='practice_chart_verifications')
    op.drop_table('practice_chart_verifications')
    op.drop_index(op.f('ix_practice_charts_profile_id'), table_name='practice_charts')
    op.drop_index(op.f('ix_practice_charts_practice_date'), table_name='practice_charts')
    op.drop_table('practice_charts')
    # ### end Alembic commands ###
