"""add contest persistence foundation

Revision ID: 8a899a61d621
Revises: 71263ef351b4
Create Date: 2026-07-28 14:14:45.436739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a899a61d621'
down_revision: Union[str, Sequence[str], None] = '71263ef351b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('category_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contests_category_key'), 'contests', ['category_key'], unique=False)
    op.create_index(op.f('ix_contests_key'), 'contests', ['key'], unique=True)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasons_key'), 'seasons', ['key'], unique=True)
    op.create_table('contest_weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'week_start', name='uq_contest_week_season_start')
    )
    op.create_index(op.f('ix_contest_weeks_season_id'), 'contest_weeks', ['season_id'], unique=False)
    op.create_index(op.f('ix_contest_weeks_week_start'), 'contest_weeks', ['week_start'], unique=False)
    op.create_table('crown_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('category_key', sa.String(length=100), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['woodchuck_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'category_key', name='uq_crown_progress_profile_category')
    )
    op.create_index(op.f('ix_crown_progress_category_key'), 'crown_progress', ['category_key'], unique=False)
    op.create_index(op.f('ix_crown_progress_profile_id'), 'crown_progress', ['profile_id'], unique=False)
    op.create_table('reward_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=150), nullable=False),
    sa.Column('reward_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['woodchuck_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'source_key', 'reward_type', name='uq_reward_grant_profile_source_type')
    )
    op.create_index(op.f('ix_reward_grants_profile_id'), 'reward_grants', ['profile_id'], unique=False)
    op.create_index(op.f('ix_reward_grants_reward_type'), 'reward_grants', ['reward_type'], unique=False)
    op.create_index(op.f('ix_reward_grants_source_key'), 'reward_grants', ['source_key'], unique=False)
    op.create_table('contest_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_week_id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('division', sa.String(length=100), nullable=False),
    sa.Column('subject_key', sa.String(length=100), nullable=False),
    sa.Column('winner_profile_id', sa.Integer(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contest_week_id'], ['contest_weeks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_profile_id'], ['woodchuck_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contest_week_id', 'contest_id', 'division', 'subject_key', name='uq_contest_result_week_contest_division_subject')
    )
    op.create_index(op.f('ix_contest_results_contest_id'), 'contest_results', ['contest_id'], unique=False)
    op.create_index(op.f('ix_contest_results_contest_week_id'), 'contest_results', ['contest_week_id'], unique=False)
    op.create_index(op.f('ix_contest_results_division'), 'contest_results', ['division'], unique=False)
    op.create_index(op.f('ix_contest_results_subject_key'), 'contest_results', ['subject_key'], unique=False)
    op.create_index(op.f('ix_contest_results_winner_profile_id'), 'contest_results', ['winner_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contest_results_winner_profile_id'), table_name='contest_results')
    op.drop_index(op.f('ix_contest_results_subject_key'), table_name='contest_results')
    op.drop_index(op.f('ix_contest_results_division'), table_name='contest_results')
    op.drop_index(op.f('ix_contest_results_contest_week_id'), table_name='contest_results')
    op.drop_index(op.f('ix_contest_results_contest_id'), table_name='contest_results')
    op.drop_table('contest_results')
    op.drop_index(op.f('ix_reward_grants_source_key'), table_name='reward_grants')
    op.drop_index(op.f('ix_reward_grants_reward_type'), table_name='reward_grants')
    op.drop_index(op.f('ix_reward_grants_profile_id'), table_name='reward_grants')
    op.drop_table('reward_grants')
    op.drop_index(op.f('ix_crown_progress_profile_id'), table_name='crown_progress')
    op.drop_index(op.f('ix_crown_progress_category_key'), table_name='crown_progress')
    op.drop_table('crown_progress')
    op.drop_index(op.f('ix_contest_weeks_week_start'), table_name='contest_weeks')
    op.drop_index(op.f('ix_contest_weeks_season_id'), table_name='contest_weeks')
    op.drop_table('contest_weeks')
    op.drop_index(op.f('ix_seasons_key'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_contests_key'), table_name='contests')
    op.drop_index(op.f('ix_contests_category_key'), table_name='contests')
    op.drop_table('contests')
    # ### end Alembic commands ###
