"""add trusted verifiers and organizations

Revision ID: b02376fe6f2f
Revises: 23b34addd30a
Create Date: 2026-07-23 01:55:23.172073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b02376fe6f2f'
down_revision: Union[str, Sequence[str], None] = '23b34addd30a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trusted_verifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trusted_verifiers_email'), 'trusted_verifiers', ['email'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('organization_type', sa.String(length=50), nullable=False),
    sa.Column('created_by_verifier_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_verifier_id'], ['trusted_verifiers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_verifier_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('verifier_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['woodchuck_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verifier_id'], ['trusted_verifiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'verifier_id', name='uq_student_verifier_connection')
    )
    op.create_index(op.f('ix_student_verifier_connections_profile_id'), 'student_verifier_connections', ['profile_id'], unique=False)
    op.create_index(op.f('ix_student_verifier_connections_verifier_id'), 'student_verifier_connections', ['verifier_id'], unique=False)
    op.create_table('student_organization_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['woodchuck_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'profile_id', name='uq_student_organization_membership')
    )
    op.create_index(op.f('ix_student_organization_memberships_organization_id'), 'student_organization_memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_student_organization_memberships_profile_id'), 'student_organization_memberships', ['profile_id'], unique=False)
    op.create_table('verifier_organization_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('verifier_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verifier_id'], ['trusted_verifiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'verifier_id', name='uq_verifier_organization_membership')
    )
    op.create_index(op.f('ix_verifier_organization_memberships_organization_id'), 'verifier_organization_memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_verifier_organization_memberships_verifier_id'), 'verifier_organization_memberships', ['verifier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verifier_organization_memberships_verifier_id'), table_name='verifier_organization_memberships')
    op.drop_index(op.f('ix_verifier_organization_memberships_organization_id'), table_name='verifier_organization_memberships')
    op.drop_table('verifier_organization_memberships')
    op.drop_index(op.f('ix_student_organization_memberships_profile_id'), table_name='student_organization_memberships')
    op.drop_index(op.f('ix_student_organization_memberships_organization_id'), table_name='student_organization_memberships')
    op.drop_table('student_organization_memberships')
    op.drop_index(op.f('ix_student_verifier_connections_verifier_id'), table_name='student_verifier_connections')
    op.drop_index(op.f('ix_student_verifier_connections_profile_id'), table_name='student_verifier_connections')
    op.drop_table('student_verifier_connections')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_trusted_verifiers_email'), table_name='trusted_verifiers')
    op.drop_table('trusted_verifiers')
    # ### end Alembic commands ###
