"""add trusted verifier invitations

Revision ID: e701fcff9301
Revises: b02376fe6f2f
Create Date: 2026-07-23 02:02:23.382211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e701fcff9301'
down_revision: Union[str, Sequence[str], None] = 'b02376fe6f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trusted_verifier_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('accepted_verifier_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accepted_verifier_id'], ['trusted_verifiers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['woodchuck_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trusted_verifier_invitations_email'), 'trusted_verifier_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_trusted_verifier_invitations_profile_id'), 'trusted_verifier_invitations', ['profile_id'], unique=False)
    op.create_index(op.f('ix_trusted_verifier_invitations_status'), 'trusted_verifier_invitations', ['status'], unique=False)
    op.create_index(op.f('ix_trusted_verifier_invitations_token_hash'), 'trusted_verifier_invitations', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trusted_verifier_invitations_token_hash'), table_name='trusted_verifier_invitations')
    op.drop_index(op.f('ix_trusted_verifier_invitations_status'), table_name='trusted_verifier_invitations')
    op.drop_index(op.f('ix_trusted_verifier_invitations_profile_id'), table_name='trusted_verifier_invitations')
    op.drop_index(op.f('ix_trusted_verifier_invitations_email'), table_name='trusted_verifier_invitations')
    op.drop_table('trusted_verifier_invitations')
    # ### end Alembic commands ###
