FROM python:3.12-slim

WORKDIR /app

COPY app/ app/
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["python", "app/main.py"]
CMD []

#CMD ["--format", "json"]
