name: terraform-ci

on:
  pull_request:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        stack:
          - environments/shared-iam
          - environments/dev
          - environments/stage

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"

      # 1) Formatting
      - name: terraform fmt (check)
        run: terraform fmt -check -recursive

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::646313139147:role/github-actions-terraform-plan
          aws-region: us-east-2

      # 2) Validate each stack WITHOUT backend/AWS
      - name: terraform init (no backend)
        working-directory: ${{ matrix.stack }}
        run: terraform init -backend=false

      - name: terraform validate
        working-directory: ${{ matrix.stack }}
        run: terraform validate

      # 3) Plan WITH backend/AWS
      - name: terraform init (backend)
        working-directory: ${{ matrix.stack }}
        run: terraform init

          #- name: terraform plan
          #working-directory: ${{ matrix.stack }}
          #run: terraform plan -no-color


      - name: terraform plan
        working-directory: ${{ matrix.stack }}
        env:
          TF_VAR_key_name: ${{ vars.TF_VAR_KEY_NAME }}
          TF_VAR_my_ip: ${{ vars.TF_VAR_MY_IP }}
        run: terraform plan -no-color -input=false
